In [1]:
# Import library
import numpy as np
import numpy.linalg as npl
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
mat = np.vstack([[1,1,1],[1,-1,2],[0,1,1]])
sol = np.vstack([3,2,2])

In [5]:
mat

array([[ 1,  1,  1],
       [ 1, -1,  2],
       [ 0,  1,  1]])

In [7]:
sol

array([[3],
       [2],
       [2]])

In [11]:
np.array([[1,1,1],[1,-1,2],[0,1,1]]).shape

(3, 3)

In [13]:
mat.shape

(3, 3)

In [15]:
npl.solve(mat,sol)

array([[1.],
       [1.],
       [1.]])